# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u043f\u043b\u0430\u043d\u0435\u0442\u0430',
                'verbose_name_plural': '\u043f\u043b\u0430\u043d\u0435\u0442\u044b',
            },
        ),
    ]
