# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u0430\u043d\u0434\u0438\u0434\u0430\u0442'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('test', 'text')]),
        ),
    ]
